In [1]:
import tensorflow as tf

In [2]:
a = tf.random.normal([4,35,8]) # 模拟成绩册 A
b = tf.random.normal([6,35,8]) # 模拟成绩册 B

In [3]:
tf.concat([a,b],axis=0) # 拼接合并成绩册

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-0.35329035,  0.784916  , -0.04776901, ...,  0.3754639 ,
          1.7867529 , -0.80459505],
        [-0.4580121 , -0.8691972 , -0.43634632, ..., -0.1546011 ,
          0.08323808, -1.4984142 ],
        [-0.0635076 , -1.5193514 ,  3.2732613 , ..., -1.3308865 ,
         -0.07938446,  0.5155528 ],
        ...,
        [-0.47147465,  0.6660076 ,  0.32654634, ...,  1.8875932 ,
          0.33133847,  0.13087037],
        [ 1.3692166 , -0.30491892,  1.1150465 , ..., -0.3134261 ,
          0.14139257, -0.04875432],
        [-0.6053942 ,  1.2652204 ,  0.8245076 , ...,  0.25851566,
         -1.9586718 , -0.89257854]],

       [[-0.50480515, -1.4061924 ,  0.21524826, ..., -1.0988458 ,
         -0.6567343 , -1.1334852 ],
        [ 0.1928806 , -0.14993896,  1.0520273 , ...,  1.8289537 ,
         -1.2232734 , -0.45168057],
        [ 0.7502085 , -0.4973999 , -0.7213101 , ...,  1.1184114 ,
          0.1628326 ,  0.18228249],
        ...,
 

In [4]:
a = tf.random.normal([10,35,4])
b = tf.random.normal([10,35,4])
tf.concat([a,b],axis=2) # 在科目维度上拼接

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.2338533 ,  0.15580685,  0.32119173, ...,  1.6024985 ,
          1.1206584 , -0.3077453 ],
        [-0.1166375 , -1.0591133 ,  0.2844041 , ..., -1.5556495 ,
          1.9061998 ,  0.19139516],
        [ 0.7930893 ,  1.1832643 , -0.43144947, ...,  1.3159965 ,
         -0.54544157, -0.23133016],
        ...,
        [ 1.588123  ,  0.19962823, -1.0678004 , ...,  0.2807046 ,
          0.44181505,  0.4231566 ],
        [ 0.46191865,  1.0601976 ,  0.8444671 , ...,  0.4739049 ,
          0.4457223 ,  1.3698069 ],
        [ 0.61291236,  0.64079624, -0.7371206 , ..., -1.1691822 ,
         -0.45924848,  0.5801284 ]],

       [[ 0.8000929 ,  0.9792188 , -0.3375994 , ..., -0.7704912 ,
          1.896365  ,  0.28482464],
        [ 0.44625142,  1.3672204 ,  0.28516558, ..., -0.32355908,
         -0.6346097 , -0.43118235],
        [-0.174726  , -0.9852187 ,  0.2231881 , ..., -0.8091514 ,
         -0.5790989 , -0.36094317],
        ...,
 

In [5]:
a = tf.random.normal([4,32,8])
b = tf.random.normal([6,35,8])
tf.concat([a,b],axis=0) # 非法拼接，其他维度长度不相同

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [4,32,8] vs. shape[1] = [6,35,8] [Op:ConcatV2] name: concat

In [ ]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=0) # 堆叠合并为 2 个班级，班级维度插入在最前

In [ ]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=-1) # 在末尾插入班级维度

tf.stack 也需要满足张量堆叠合并条件，它需要所有待合并的张量 shape 完全一致才可
合并。我们来看张量 shape 不一致时进行堆叠合并发生的错误，例如：

In [ ]:
a = tf.random.normal([35,4])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=-1) # 非法堆叠操作，张量 shape 不相同

In [7]:
x = tf.random.normal([10,35,8])
# 等长切割为 10 份
result = tf.split(x, num_or_size_splits=10, axis=0)
len(result) # 返回的列表为 10 个张量的列表


10

In [ ]:
result[0] # 查看第一个班级的成绩册张量

In [ ]:
x = tf.random.normal([10,35,8])

In [ ]:
# 自定义长度的切割，切割为 4 份，返回 4 个张量的列表 result
result = tf.split(x, num_or_size_splits=[4,2,2,2] ,axis=0)
len(result)